name: Flake checks
on:
  workflow_dispatch:
  pull_request:
      paths:
      - '**.nix'
  push:
    branches: ["main"]
    paths:
      - '**.nix'

jobs:
  check-formatting:
    name: "check nix formatting"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd0112011b244d6f43aece5ff8411b7815e01b
        with:
          persist-credentials: false

      - name: "Install Nix"
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd

      - name: "Evaluate formatting checks"
        run: |
          system=$(nix eval --raw --impure --expr builtins.currentSystem)

          # Evaluate formatting check to verify tree-wide formatting.
          nix build -L .#checks."${system}".formatting
