name: "Build and deploy documentation"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - docs/**
      - modules/**
      - flake.lock
      - lib.nix
      - .github/workflows/deploy-docs.yml

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v5
      - name: Print latest_commit
        run: "echo Latest commit is: ${{ github.sha }}"

      - name: Check latest commit is less than a day
        id: should_run
        if: ${{ github.event_name == 'schedule' }}
        continue-on-error: true
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "::set-output name=should_run::false"

  publish:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            substituters = https://cache.nixos.org/ https://feel-co.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= feel-co.cachix.org-1:nwEFNnwZvtl4KKSH5LDg+/+K7bV0vcs6faMHAJ6xx0w=

      - name: Build HTML documentation
        run: |
          nix build .#docs-html -Lv

          # Copy the build manual to the public dir
          # which we will serve
          cp -r result/share/doc public

      - name: Deploy built documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: hjem.feel-co.org

